spring:
  application:
    name: zuul-proxy
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    baseUrl: ${vcap.services.zipkin-server.credentials.uri:http://localhost:9411}
      
server:
  port: ${PORT:8080}

eureka:
  client:
    serviceUrl:
       defaultZone: ${vcap.services.eureka-service-discovery.credentials.uri:http://localhost:8761/eureka/}
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    preferIpAddress: true

---
spring:
  profiles: cloud
eureka:
  instance:
    nonSecurePort: 80
    preferIpAddress: false
