server:
  port: 8080

eureka:
  instance:
     preferIpAddress: true
  client:
    serviceUrl:
       defaultZone: http://localhost:8761/eureka/

#cloud:
#  conablefig:
#    failFast: true
#    discovery:
#      end: true
