server:
  port: ${vcap.application.port:8080}

eureka:
  client:
    serviceUrl:
       defaultZone: http://192.168.123.4:8761/eureka/
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
    preferIpAddress: true

#cloud:
#  conablefig:
#    failFast: true
#    discovery:
#      end: true

---
spring:
  profiles: cloud
eureka:
  instance:
    nonSecurePort: 80
    preferIpAddress: false
